# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tictactoe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftictactoe.proto\"\x11\n\x0f\x44\x61teTimeRequest\",\n\x16\x43lockAdjustmentRequest\x12\x12\n\nadjustment\x18\x01 \x01(\x03\"Q\n\x10\x44\x61teTimeResponse\x12\x11\n\tdate_time\x18\x01 \x01(\t\x12\x14\n\x0cserver_clock\x18\x02 \x01(\x03\x12\x14\n\x0c\x61\x64just_clock\x18\x03 \x01(\x08\"\x12\n\x10GetLeaderRequest\"#\n\x11GetLeaderResponse\x12\x0e\n\x06leader\x18\x01 \x01(\t\"\'\n\x14StartElectionRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"8\n\x15StartElectionResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06leader\x18\x02 \x01(\t\"#\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"\x13\n\x11HeartbeatResponse\"4\n\x10StartGameRequest\x12\x0f\n\x07player1\x18\x01 \x01(\t\x12\x0f\n\x07player2\x18\x02 \x01(\t\"5\n\x11StartGameResponse\x12\x0f\n\x07player1\x18\x01 \x01(\t\x12\x0f\n\x07player2\x18\x02 \x01(\t\"6\n\x10SetSymbolRequest\x12\x12\n\ncoordinate\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"7\n\x11SetSymbolResponse\x12\x12\n\ncoordinate\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"!\n\x10ListBoardRequest\x12\r\n\x05\x62oard\x18\x01 \x01(\t\"\"\n\x11ListBoardResponse\x12\r\n\x05\x62oard\x18\x01 \x01(\t2|\n\rBerkeleyClock\x12\x32\n\x0bGetDateTime\x12\x10.DateTimeRequest\x1a\x11.DateTimeResponse\x12\x37\n\tSyncClock\x12\x17.ClockAdjustmentRequest\x1a\x11.DateTimeResponse2\xb7\x01\n\rBullyElection\x12>\n\rStartElection\x12\x15.StartElectionRequest\x1a\x16.StartElectionResponse\x12\x32\n\tGetLeader\x12\x11.GetLeaderRequest\x1a\x12.GetLeaderResponse\x12\x32\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponse2\xad\x01\n\tTicTacToe\x12\x34\n\tStartGame\x12\x11.StartGameRequest\x1a\x12.StartGameResponse\"\x00\x12\x34\n\tSetSymbol\x12\x11.SetSymbolRequest\x1a\x12.SetSymbolResponse\"\x00\x12\x34\n\tListBoard\x12\x11.ListBoardRequest\x1a\x12.ListBoardResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tictactoe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATETIMEREQUEST._serialized_start=19
  _DATETIMEREQUEST._serialized_end=36
  _CLOCKADJUSTMENTREQUEST._serialized_start=38
  _CLOCKADJUSTMENTREQUEST._serialized_end=82
  _DATETIMERESPONSE._serialized_start=84
  _DATETIMERESPONSE._serialized_end=165
  _GETLEADERREQUEST._serialized_start=167
  _GETLEADERREQUEST._serialized_end=185
  _GETLEADERRESPONSE._serialized_start=187
  _GETLEADERRESPONSE._serialized_end=222
  _STARTELECTIONREQUEST._serialized_start=224
  _STARTELECTIONREQUEST._serialized_end=263
  _STARTELECTIONRESPONSE._serialized_start=265
  _STARTELECTIONRESPONSE._serialized_end=321
  _HEARTBEATREQUEST._serialized_start=323
  _HEARTBEATREQUEST._serialized_end=358
  _HEARTBEATRESPONSE._serialized_start=360
  _HEARTBEATRESPONSE._serialized_end=379
  _STARTGAMEREQUEST._serialized_start=381
  _STARTGAMEREQUEST._serialized_end=433
  _STARTGAMERESPONSE._serialized_start=435
  _STARTGAMERESPONSE._serialized_end=488
  _SETSYMBOLREQUEST._serialized_start=490
  _SETSYMBOLREQUEST._serialized_end=544
  _SETSYMBOLRESPONSE._serialized_start=546
  _SETSYMBOLRESPONSE._serialized_end=601
  _LISTBOARDREQUEST._serialized_start=603
  _LISTBOARDREQUEST._serialized_end=636
  _LISTBOARDRESPONSE._serialized_start=638
  _LISTBOARDRESPONSE._serialized_end=672
  _BERKELEYCLOCK._serialized_start=674
  _BERKELEYCLOCK._serialized_end=798
  _BULLYELECTION._serialized_start=801
  _BULLYELECTION._serialized_end=984
  _TICTACTOE._serialized_start=987
  _TICTACTOE._serialized_end=1160
# @@protoc_insertion_point(module_scope)
